### ISSUE TITLE
Users can't close popup in mobile browsers

### ISSUE THREAD

**Issue by MorganaLF** [RampNetwork/ramp-instant-sdk#4]
**Expected behavior:**

In mobile browsers users can close popup with close icon.

**Actual behavior:**

There is no close icon or any ways to close popup.

**Steps to reproduce the behavior:**

1. Create instance of widget:

```
 const widget = new RampInstantSDK({
      variant: 'auto',
    }).show();
```

**2. Open popup in Chrome/Firefox mobile browser**

![photo_2021-01-29_13-15-47](https://user-images.githubusercontent.com/38564412/106262838-9d313000-6234-11eb-8ba8-58b0423515e2.jpg)

**Comment by Mysticalgirl007** [comment]
This ramp helps us to buy using fiat, ex: my bank card disabled my online payments with crypto, how can I start using my wallet then?
